name: kickin_media_widget
description: "A Flutter widget for displaying media (images/videos) with swiping, video controls, and more."
version: 1.0.0+2

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.5.0
  chewie: ^1.4.3
  visibility_detector: ^0.4.0+2
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

repository: https://github.com/Kickinapp/kickin_media_widget


